apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fatal-barracuda-nodejs 
  janus-idp.io/tekton: fatal-barracuda-nodejs
  backstage.io/kubernetes-id: fatal-barracuda-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fatal-barracuda-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  