apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fatal-barracuda-nodejs-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/fatal-barracuda-nodejs