apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fatal-barracuda-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fatal-barracuda-nodejs 
  name: fatal-barracuda-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fatal-barracuda-nodejs 
